# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 斯文怪谈
sub-title: Babbling gently ...
description: >- # this means to ignore newlines until "baseurl:"
  My personal giberrish
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.yusiwen.cn" # the base hostname & protocol for your site, e.g. http://example.com
version: 1.0.1

# About/contact
author:
  name: Siwen Yu
  description: A passionate <strong>developer and researcher</strong>.
  gravatar: bfb364f5613b11ae32cffd3f7e0bb10c
  contact:
    github:    https://github.com/yusiwen
    # facebook:  <hide>
    twitter:   https://twitter.com/yusiwen
    email:     mailto:yusiwen@gmail.com

# Build settings
markdown: kramdown
plugins: [jekyll-paginate]
paginate: 10 # pagination basted on number of posts
highlighter: rouge

exclude: ["Gemfile", "Gemfile.lock", "README.md", 'watch.sh'] # files to exclude

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
