# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

plugins: [jekyll-paginate]

paginate: 10 # pagination basted on number of posts

markdown: redcarpet

redcarpet:
    extensions: [footnotes]

highlighter: pygments

github: [Repository metadata]

exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude
